### ISSUE TITLE
ft-lambda: handle already used R, P, T generic placeholders

### ISSUE THREAD

**Issue by lalmeras** [igloo-project/bindgen#3]
For now, bindgen does not handle already used generic placeholders.

If we bind a GenericClass\<P\>, it fails because we use P placeholder twice (one from the bound class, one from the binding).

[edited 29.11.2018 to escape tags, so that issue can be read]

**Comment by nfekete** [comment]
Sorry, it's not ready yet. I'll get back to it later.

**Comment by nfekete** [comment]
It should be ready now.

**Comment by lalmeras** [comment]
This issue was fixed with #14 merge. Released on master, version 4.0.2, thanks to @nfekete
