### ISSUE TITLE
Type annotations are not handled correctly

### ISSUE THREAD

**Issue by nfekete** [igloo-project/bindgen#8]
In JDK 8 `ElementType.TYPE_USE` got introduced which makes it possible to annotate a type on _type use_. Type annotations like `@Nullable`, `@NotNull` etc. are prime examples of this. Bindgen doesn't handle these cases correctly when run through `javac`, because `AnnotatedType.toString()` used at https://github.com/igloo-project/bindgen/blob/07327351e85e6f064608cd7928cb4f17a0ebe7af/processor/src/main/java/org/bindgen/processor/util/BoundProperty.java#L62 in `javac` returns a similar string:
```
(@TypeAnnotation :: TypeName)
```
which is unexpected by the processor, and therefore generates invalid java code. Under Eclipse Compiler for Java, it happens to run correctly, because of a different `toString()` implementation on `AnnotatedType` that returns only the type name.

**Comment by lalmeras** [comment]
Branch master updated to 4.0.1 with this fix. Thanks !

**Comment by nfekete** [comment]
My pleasure. Thank you for maintaining this valuable project!

**Comment by nfekete** [comment]
This fix is incomplete. I would submit a pull-request for the (more) complete fix in bb4d574 but it can only be merged on top of #11

**Comment by lalmeras** [comment]
Reopen to allow @nfekete to complete this fix, once #11 will be merged.

**Comment by lalmeras** [comment]
This issue was fixed with #14 merge. Released on master, version 4.0.2.
